### ISSUE TITLE
for training

### ISSUE THREAD

**Issue by SusannaWull** [ucfnlp/multidoc_summarization#2]

**Comment by loganlebanoff** [comment]
Thank you for your interest in my work! The benefit of using PG-MMR is that it can use a pre-trained model trained on a single-document dataset like CNN/DM and then run on a multi-document dataset at test-time without any additional training. 

Do you want to train on a different single-document dataset than CNN/DM, or do you want to train on a multi-document dataset? If you want a different single-document dataset, this will be a bit difficult to do. You can go to Abigail See's github (https://github.com/abisee/pointer-generator) on how to train the original PG, but you will have to do a great deal of pre-processing to get it to work with a new dataset. If you want to train on a multi-document dataset, PG-MMR is not meant to be trained on multi-document datasets, which is the beauty of the method.

If you want to test on a new multi-document dataset, there instructions on how to do so on the README.

**Comment by SusannaWull** [comment]
Thanks! I have tested on other English news using your method, but I got the terrible results that are all ', ' or '.'. Can you give some explanation?

**Comment by loganlebanoff** [comment]
I have a just made a fix to the README, which is that you must include the --pg_mmr flag when doing testing. Can you try again with that flag?

If that doesn't work, can you try running on the example_custom_dataset and let me know what the output is for that?

**Comment by yashkumaratri** [comment]
I tried running with the example_custom_dataset and the inference is stuck at 

![image](https://user-images.githubusercontent.com/8272814/68653201-38b38380-0551-11ea-923f-0f1fda076ea3.png)

Can you tell me what's going on ?

I just ran it with default settings as provided in readme.
I left it running for 12 hours and still no output.

**Comment by SusannaWull** [comment]
Did you run the "convert_data.py" file? I think it would work if you can modify the code to fit the data format or prepare the suitable dataset.
Another suggestion for you is to read the other paper of "Point-genertor network",&nbsp;https://github.com/abisee/pointer-generator.







------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yash Kumar Atri"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月12日(星期二) 下午4:05
收件人:&nbsp;"ucfnlp/multidoc_summarization"<multidoc_summarization@noreply.github.com&gt;;
抄送:&nbsp;"Luky Wu"<747126366@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ucfnlp/multidoc_summarization] for training (#2)




I tried running with the example_custom_dataset and the inference is stuck at
 

 
Can you tell me what's going on ?
 
I just ran it with default settings as provided in readme.

**Comment by yashkumaratri** [comment]
It's working fine, Just had some issues in the environment.

**Comment by Eoin-McMahon** [comment]
@yashkumaratri  How did you fix the error? I am having the same problem

**Comment by khoaiha12** [comment]
@yashkumaratri i have same problem.
